### ISSUE TITLE
TypeError error when run synthesis.py

### ISSUE THREAD

**Issue by wann31828** [xcmyz/FastSpeech#12]
Hi scmyz

I have train a model to step 172000 use train.py , and I want to use this model to synthesis ,
but when I run synthesis.py , I meet TypeError during the synthesis .
" TypeError: forward() missing 2 required positional arguments: 'src_seq' and 'src_pos' "
do I miss something during training or synthesis ? 

thanks
 
here is the full error log :
---------------------------------------------------------------------------------------------
(Tacotron) [wann31828@glogin1 FastSpeech]$ python synthesis.py
/home/wann31828/anaconda3/envs/Tacotron/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/wann31828/anaconda3/envs/Tacotron/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/wann31828/anaconda3/envs/Tacotron/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/wann31828/anaconda3/envs/Tacotron/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Model Have Been Loaded.
Traceback (most recent call last):
  File "synthesis.py", line 91, in <module>
    synthesis_griffin_lim(words, model, alpha=1.0, mode="normal")
  File "synthesis.py", line 45, in synthesis_griffin_lim
    mel, mel_postnet = model(text, pos, alpha=alpha)
  File "/home/wann31828/anaconda3/envs/Tacotron/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wann31828/anaconda3/envs/Tacotron/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/wann31828/anaconda3/envs/Tacotron/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/wann31828/anaconda3/envs/Tacotron/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/home/wann31828/anaconda3/envs/Tacotron/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/home/wann31828/anaconda3/envs/Tacotron/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 2 required positional arguments: 'src_seq' and 'src_pos'

**Comment by xcmyz** [comment]
Don't use multiple GPUs to synthesize.

**Comment by wann31828** [comment]
goit it , thanks
