### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by tingyang01** [xcmyz/FastSpeech#3]
Hello, 
I tried train FastSpeech with alignment_target and dataset on TeslaV100.
but I found the error like this.
Traceback (most recent call last):
  File "train_accelerated.py", line 191, in <module>
    main(args)
  File "train_accelerated.py", line 109, in main
    length_target=alignment_target)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/fastspeech/FastSpeech/FastSpeech.py", line 33, in forward
    decoder_output = self.decoder(length_regulator_output, decoder_pos)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/fastspeech/FastSpeech/transformer/Models.py", line 141, in forward
    slf_attn_mask=slf_attn_mask)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/fastspeech/FastSpeech/transformer/Layers.py", line 125, in forward
    enc_input, enc_input, enc_input, mask=slf_attn_mask)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/fastspeech/FastSpeech/transformer/SubLayers.py", line 60, in forward
    output, attn = self.attention(q, k, v, mask=mask)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/fastspeech/FastSpeech/transformer/Modules.py", line 21, in forward
    attn = attn.masked_fill(mask, -np.inf)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 337, in masked_fill
    return self.clone().masked_fill_(mask, value)
RuntimeError: CUDA out of memory. Tried to allocate 316.50 MiB (GPU 0; 15.75 GiB total capacity; 14.15 GiB already allocated; 146.88 MiB free; 317.24 MiB cached)
Could explain the reason to me?

**Comment by xcmyz** [comment]
You may need more GPUs or lower the value of batch_size.

**Comment by bushaev** [comment]
How do you set up a multi-gpu training ?

**Comment by xcmyz** [comment]
CUDA_VISIBLE_DEVICES=0,1,2,3 python train_accelerated.py

**Comment by zhangyizhong17** [comment]
the same error occurred to me once. However after that, I used a wrong environment by mistake (torch0.4.1 and CUDA9.0), it worked!!!! which is weird...

**Comment by 756890911** [comment]
我通过降低batch_size运行起了程序，但是需要降到4才能跑起来，应该是因为电脑配置不够，最好还是连服务器跑程序吧
