### ISSUE TITLE
how to solve this bug?

### ISSUE THREAD

**Issue by lzkzls** [xcmyz/FastSpeech#54]
Traceback (most recent call last):
  File "preprocess.py", line 59, in <module>
    main()
  File "preprocess.py", line 42, in main
    tacotron2 = get_Tacotron2()
  File "/home/workspace/fastspeech/FastSpeech-master/utils.py", line 69, in get_Tacotron2
    model.load_state_dict(torch.load(checkpoint_path)['state_dict'])
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 564, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x0a'.

**Comment by xcmyz** [comment]
Did you use the same tacotron2 pretrained model as referred in this repo?

**Comment by lzkzls** [comment]
Thank you! It has been solved. I did not use the correct Tacotron2 model.

**Comment by Ankita-020696** [comment]
> Thank you! It has been solved. I did not use the correct Tacotron2 model.
 
 @lzkzls I am getting same error, can you please help me to solve it?

**Comment by Ankita-020696** [comment]
@lzkzls I am getting same error, can you please help me me to fix it?

Thanks
