### ISSUE TITLE
synthesis error

### ISSUE THREAD

**Issue by BuaaAlban** [xcmyz/FastSpeech#69]
I can generate the wav with G-Lim, but failed with waveglow and tacotron2.
**For waveglow:**
Traceback (most recent call last):
  File "synthesis.py", line 69, in <module>
    "results", words + "_" + str(num) + "_waveglow.wav"))
  File "/scratch/workspace/bokangz/project/FastSpeech-master/waveglow/inference.py", line 36, in inference
    audio = waveglow.infer(mel, sigma=sigma)
  File "/scratch/workspace/bokangz/project/FastSpeech-master/glow.py", line 280, in infer
    output = self.WN[k]((audio_0, spect))
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/fastSpeech/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch/workspace/bokangz/project/FastSpeech-master/glow.py", line 166, in forward
    torch.IntTensor([self.n_channels]))
RuntimeError: /pytorch/torch/csrc/jit/fuser/cuda/fused_kernel.cpp:202: a PTX JIT compilation failed

**for tacotron2**
Traceback (most recent call last):
  File "synthesis.py", line 71, in <module>
    tacotron2 = utils.get_Tacotron2()
  File "/scratch/workspace/bokangz/project/FastSpeech-master/utils.py", line 70, in get_Tacotron2
    model.load_state_dict(torch.load(checkpoint_path)['state_dict'])
KeyError: 'state_dict'

**Comment by xcmyz** [comment]
You need download Tacotron2's model from https://github.com/NVIDIA/tacotron2

**Comment by BuaaAlban** [comment]
> You need download Tacotron2's model from https://github.com/NVIDIA/tacotron2
I indeed download it from the link, maybe NVIDIA has updated the model???  
Ihave changed the key 
model.load_state_dict(torch.load(checkpoint_path)['state_dict'])--》['model'], but the keys for the model are different from the model definition.
Can you give me a link for the old one ?

**Comment by BuaaAlban** [comment]
> You need download Tacotron2's model from https://github.com/NVIDIA/tacotron2
But this problem still exist
File "/scratch/workspace/bokangz/project/FastSpeech-master/glow.py", line 166, in forward
torch.IntTensor([self.n_channels]))
RuntimeError: /pytorch/torch/csrc/jit/fuser/cuda/fused_kernel.cpp:202: a PTX JIT compilation failed



#---------------------------
sovled by comment line 33 in glow.py #@torch.jit.trace
