### ISSUE TITLE
ModuleNotFoundError: No module named 'glow'

### ISSUE THREAD

**Issue by ccuiyuhan** [xcmyz/FastSpeech#77]
when i run this project in django i met：

Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Anaconda\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Anaconda\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\cuiyuhan\PycharmWorkplace\speech-synthesis\testDjango\text_to_speech\views.py", line 126, in english
    audio_path = synthesis_tacotron.main(textcontent,tones)
  File "D:\cuiyuhan\PycharmWorkplace\speech-synthesis\testDjango\tacotron2_english\synthesis_tacotron.py", line 71, in main
    wave_glow = utils.get_WaveGlow()
  File "D:\cuiyuhan\PycharmWorkplace\speech-synthesis\testDjango\tacotron2_english\utils.py", line 56, in get_WaveGlow
    wave_glow = torch.load(waveglow_path)['model']
  File "C:\Users\yangl\AppData\Roaming\Python\Python36\site-packages\torch\serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "C:\Users\yangl\AppData\Roaming\Python\Python36\site-packages\torch\serialization.py", line 538, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'glow'

but i didnt met this error when i run the project singly. 
i dont know how to solve it，hope some help please

**Comment by xcmyz** [comment]
You need put `glow.py` in root path.

**Comment by ccuiyuhan** [comment]
> You need put `glow.py` in root path.

thanks for replying ，i solve it by your method.But why does this happen？

**Comment by xcmyz** [comment]
> > You need put `glow.py` in root path.
> 
> thanks for replying ，i solve it by your method.But why does this happen？

waveglow need `glow.py`.
