### ISSUE TITLE
RuntimeError: shape '[1, 1, 155520]' is invalid for input of size 311040 [custom data training]

### ISSUE THREAD

**Issue by Ahmad-noborders** [xcmyz/FastSpeech#79]
hi @xcmyz  thank you so much for your work. i am training it on korean data. i have setup all my data in the data folder and here is detail of my data

Sample rate: 44100

Channels: 1

Subtype:`` PCM_16

 i have changed the sample rate in audio/hparams.py file with 44100. but i am still getting error

 i have also changed the text/symbols.py file with korean letters.

Traceback (most recent call last): File "preprocess.py", line 61, in <module> main() File "preprocess.py", line 34, in main preprocess_ljspeech(path) File "preprocess.py", line 19, in preprocess_ljspeech metadata = ljspeech.build_from_path(in_dir, out_dir) File "/content/drive/My Drive/voice/FastSpeech/data/ljspeech.py", line 15, in build_from_path out.append(_process_utterance(out_dir, index, wav_path, text)) File "/content/drive/My Drive/voice/FastSpeech/data/ljspeech.py", line 26, in _process_utterance mel_spectrogram = Audio.tools.get_mel(wav_path).numpy().astype(np.float32) File "/content/drive/My Drive/voice/FastSpeech/audio/tools.py", line 29, in get_mel melspec = _stft.mel_spectrogram(audio_norm) File "/content/drive/My Drive/voice/FastSpeech/audio/stft.py", line 154, in mel_spectrogram magnitudes, phases = self.stft_fn.transform(y) File "/content/drive/My Drive/voice/FastSpeech/audio/stft.py", line 58, in transform input_data = input_data.view(num_batches, 1, num_samples) RuntimeError: shape '[1, 1, 155520]' is invalid for input of size 311040

can you please help me solving this issue. Thanks

**Comment by xcmyz** [comment]
You also need change hop_length and win_length.

**Comment by Ahmad-noborders** [comment]
@xcmyz  can you please explain what is hop_length and win_length. these are defined on the base of what.

**Comment by xcmyz** [comment]
You need to learn how to calculate mel spectrogram.
