### ISSUE TITLE
error in new commit

### ISSUE THREAD

**Issue by Ahmad-noborders** [xcmyz/FastSpeech#81]
hi @xcmyz 
after successful run of preprocess.py 
when i run train.py it gives following error
```
Use FastSpeech
Model Has Been Defined
Number of TTS Parameters: 25367169
Load data to buffer
100% 1132/1132 [32:11<00:00,  1.71s/it]
cost 1931.72s to load all data into buffer.
Defined Optimizer and Loss Function.

---Start New Training---

Traceback (most recent call last):
  File "train.py", line 193, in <module>
    main(args)
  File "train.py", line 106, in main
    length_target=duration)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 143, in forward
    return self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/fastspeech3/FastSpeech/model.py", line 42, in forward
    mel_max_length=mel_max_length)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/fastspeech3/FastSpeech/modules.py", line 82, in forward
    output = self.LR(x, target, mel_max_length=mel_max_length)
  File "/content/drive/My Drive/fastspeech3/FastSpeech/modules.py", line 72, in LR
    output = alignment @ x
RuntimeError: Expected tensor to have size 152 at dimension 1, but got size 91 for argument #2 'batch2' (while checking arguments for bmm)
```

**Comment by Ahmad-noborders** [comment]
if i run it on Gpu it gives same traceback with this error.
in torch  1.2.0 : 
`RuntimeError: invalid argument 6: wrong matrix size at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:499`

in torch 1.5.0 last line of same error is 
`RuntimeError: invalid argument 6: wrong matrix size at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:549`

**Comment by MorganCZY** [comment]
Hi, an error occured to me when running preprocess.py with the latest code version. It seems the processing is jammed as shown in the following picture. Have you had this error? if yes, could you introduce your solutions?
![image](https://user-images.githubusercontent.com/33675916/89020238-2da7ba00-d351-11ea-8beb-1f294e770520.png)

**Comment by xcmyz** [comment]
> Hi, an error occured to me when running preprocess.py with the latest code version. It seems the processing is jammed as shown in the following picture. Have you had this error? if yes, could you introduce your solutions?
> ![image](https://user-images.githubusercontent.com/33675916/89020238-2da7ba00-d351-11ea-8beb-1f294e770520.png)

`            futures.append(_process_utterance(out_dir, index, wav_path, text))
            index = index + 1
    return futures`

**Comment by MorganCZY** [comment]
But what's the reason for this "deadlock" in the current code(with executor.submit....)?

**Comment by MorganCZY** [comment]
It seems because there are torch tensor operations in multi processing. I located that the code came to a deadlock when running the line as shown in the following picture. If I replace torch.FloatTensor with array, it passes. Could someone explain it? 
![image](https://user-images.githubusercontent.com/33675916/89031349-e6c3bf80-d364-11ea-886d-880ec161f8f3.png)

**Comment by xcmyz** [comment]
> It seems because there are torch tensor operations in multi processing. I located that the code came to a deadlock when running the line as shown in the following picture. If I replace torch.FloatTensor with array, it passes. Could someone explain it?
> ![image](https://user-images.githubusercontent.com/33675916/89031349-e6c3bf80-d364-11ea-886d-880ec161f8f3.png)

Because of the version of pytorch?

**Comment by YinPing-Cho** [comment]
hi @xcmyz, it seems this issue opened by @Ahmad-noborders is also reproduced here in my case. By printing the Tensors out, I find unresolved mismatches between the sizes of "duration" Tensors from the dataset and the "out" Tensors produced by DurationPredictor().
![fastspeech](https://user-images.githubusercontent.com/63432757/89167737-5a0c4200-d5ae-11ea-9ca2-da582a333904.PNG)

**Comment by akashicMarga** [comment]
@Ahmad-noborders were you able to resolve the issue?

**Comment by Ahmad-noborders** [comment]
@singhaki  nope i had to move to tacotron2 which is base of this repo
